---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Build Rocky9 SSH Docker image
      community.docker.docker_image:
        name: rocky9-ssh-img
        build:
          path: "./dockerfiles"
          dockerfile: Dockerfile.rocky9
        source: build
        state: present
    
    - name: Display connection info
      debug:
        msg: "Container built successfully! To run: docker run -d -p 2223:22 --name rocky9-ssh rocky9-ssh-img"
    
    - name: Display SSH connection info  
      debug:
        msg: "To connect via SSH: ssh -i dockerfiles/id_key_genericuser -p 2223 genericuser@localhost"