---
- name: Config Docker Registry
  hosts: all
  become: yes

  tasks:
    - name: Create dockerfiles directory
      file:
        path: /home/vagrant/dockerfiles
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Generate SSH key pair for container access on VM
      openssh_keypair:
        path: /home/vagrant/dockerfiles/id_key_genericuser
        type: rsa
        size: 4096
        comment: "SSH key for Rocky9 and Alpine container access"
        force: yes
        owner: vagrant
        group: vagrant
      become: no
      become_user: vagrant

    - name: Assicure python3-pip is installed
      dnf:
        name: python3-pip
        state: present

    - name: Install required python packages
      pip:
        name:
          - requests
          - docker
          - pyyaml
        executable: pip3
    - name: Add official docker repo
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo  #to avoid recursive dowloads
    - name: Install Docker
      dnf:
       name:
         - docker-ce                    ## If not present, install Docker
         - docker-ce-cli
         - containerd.io
       state: present
    - name: Lounch Docker service
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Add vagrant user to docker group 
      user:
        name: vagrant
        groups: docker
        append: yes
    
    - name: Reset SSH connection to allow user group changes
      meta: reset_connection

    - name: Create directory for registry data
      file:
        path: /registry
        state: directory
    - name: Create registry container
      community.docker.docker_container:
        name: registry
        image: registry:2
        state: started
        volumes:
          - registry-data:/var/lib/registry
        ports:
          - "5000:5000"
    