---
- name: Complete Container Pipeline
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    container_runtime: "docker"  # default, can be overridden with -e container_runtime=podman
    
  roles:
    - registry_setup      # 1. Setup registry
    - container_builder   # 2. Build + Push  
    - container_runner    # 3. Run containers


## Vault : 
# ENCRYPT
# for file in dockerfiles/*; do ansible-vault encrypt "$file" --vault-password-file .vault_pass; done
# DECRYPT
# for file in dockerfiles/*; do ansible-vault decrypt "$file" --vault-password-file .vault_pass; done


# RUN
##   ansible-playbook start.yaml -v -e "container_runtime=podman" --vault-password-file .vault_pass
##   ansible-playbook playbook.yaml --vault-password-file .vault_pass

# memo : Basic structure of role directorues:

# name_role/
# ├── defaults/          # vars with LOW priority
# │   └── main.yaml
# ├── vars/             # Vars with HIGH priority
# │   └── main.yaml
# ├── tasks/            # List of tasks to execute
# │   └── main.yaml
# ├── handlers/         # Tasks triggered by notify
# │   └── main.yaml
# ├── files/            # Static files to copy
# ├── templates/        # Jinja2 templates
# ├── meta/             # Metadata and dependencies
# │   └── main.yaml
# └── README.md         # Documentation


# remember to pay attention of ssh directory and file permissions and ownership (700 for dir, 600 for private key, 644 for public key) a big rottura di balls

# ansible-vault encrypt dockerfiles/secrets.yml --vault-password-file .vault_pass
# ansible-vault decrypt dockerfiles/secrets.yml --vault-password-file .vault_pass