---
- name: Complete Container Pipeline
  hosts: localhost
  connection: local
  gather_facts: false
  
  roles:
    - registry_setup      # 1. Setup registry
    - container_builder   # 2. Build + Push  
    - container_runner    # 3. Run containers

  post_tasks:
    - name: Pipeline completato con successo
      debug:
        msg: |
          PIPELINE complete! 
          Registry: http://localhost:5000
          CentOS SSH: ssh -i dockerfiles/id_key_genericuser -p 2222 genericuser@127.0.0.1
          Rocky9 SSH: ssh -i dockerfiles/id_key_genericuser -p 2223 genericuser@127.0.0.1
          ## 127.0.0.1 is the loopback address, it always refers to the ===  localhost ===.

## Vault : 
# ENCRYPT
# echo "goccia" > .vault_pass && for file in dockerfiles/*; do ansible-vault encrypt "$file" --vault-password-file .vault_pass; done
# DECRYPT
# for file in dockerfiles/*; do ansible-vault decrypt "$file" --vault-password-file .vault_pass; done
# RUN
##   ansible-playbook start.yaml -v
##   ansible-playbook playbook.yaml --vault-password-file password_file.txt

# memo : Basic structure of role directorues:

# name_role/
# ├── defaults/          # vars with LOW priority
# │   └── main.yaml
# ├── vars/             # Vars with HIGH priority
# │   └── main.yaml
# ├── tasks/            # List of tasks to execute
# │   └── main.yaml
# ├── handlers/         # Tasks triggered by notify
# │   └── main.yaml
# ├── files/            # Static files to copy
# ├── templates/        # Jinja2 templates
# ├── meta/             # Metadata and dependencies
# │   └── main.yaml
# └── README.md         # Documentation


# remember to pay attention of ssh directory and file permissions and ownership (700 for dir, 600 for private key, 644 for public key) a big rottura di balls