apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: anmedyns/hello-prometheus:v1
        # namespace: monitoring
        ports:
        - containerPort: 321
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: monitoring
  labels:
    app: flask-app
spec:
  ports:
  - port: 321
    name: metrics
  selector:
    app: flask-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 10s



###  black-box configuration - prober for monitoring external services like google


apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: google-blackbox
  namespace: monitoring
  labels:
    release: prometheus   # important for prometheus to discover the probe
spec:
  jobName: google-blackbox
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    scheme: http
  targets:
    staticConfig:
      static:
        - https://www.google.com