Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"  
  config.vm.box_version = "4.3.12"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "install_pak.yaml"
end
end