#!/bin/bash                                                                 #shebang (specify the interpreter which run the script)
# am-i-root.sh:   Am I root or not?                                         #comment
 
ROOT_UID=0   # Root has $UID 0.                                             #crea una variabile con valore 0
 
if [ "$UID" -eq "$ROOT_UID" ]  # Will the real "root" please stand up?      #esegue una verifica con condizione, se e' vera 
then
  echo "You are root."
else
  echo "You are just an ordinary user (but mom loves you just the same)."
fi
 
exit 0                                                                      #imposta l'exit_status a 0 
# ============================================================= #
# Code below will not execute, because the script already exited.
 
# An alternate method of getting to the root of matters:
 
ROOTUSER_NAME=root
 
username=`id -nu`              # Or...   username=`whoami`=
if [ "$username" = "$ROOTUSER_NAME" ]
then
  echo "Rooty, toot, toot. You are root."                           #piu' o meno la stessa cosa , solamente che in questo caso usa una sintassi leggermente diversa e confronta questa volta il nome dello user e non l'UUID
else
  echo "You are just a regular fella."
fi