Vagrant.configure("2") do |config|
  config.vm.define "debian" do |debian|
   debian.vm.box = "generic/debian11"
   debian.vm.box_version = "4.3.12"
   debian.vm.network "private_network", ip: "192.168.56.20"
   debian.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update --fix-missing
    sudo apt update && sudo apt install -y docker.io
    echo -n "\033[31mversion--->\033[0m" && docker --version
    SHELL
  end

  config.vm.define "debian2" do |debian2|
   debian2.vm.box = "generic/debian11"
   debian2.vm.box_version = "4.3.12"
   debian2.vm.network "private_network", ip: "192.168.56.10"
   debian2.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update --fix-missing
    sudo apt update && sudo apt install -y docker.io
    echo -n "\033[31mversion--->\033[0m" && docker --version
    SHELL
  end
end