---
- name: Run Docker containers from registry
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ registry_url }}/{{ item.image }}:latest"
    state: started
    ports:
      - "{{ item.ssh_port }}:22"
    restart_policy: always
    pull: yes
  loop: "{{ containers_to_run }}"
  when: container_runtime == 'docker'

- name: Run Podman containers from registry
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ registry_url }}/{{ item.image }}:latest"
    state: started
    ports:
      - "{{ item.ssh_port }}:22"
    restart_policy: always
    pull: always
    tls_verify: false
  loop: "{{ containers_to_run }}"
  when: container_runtime == 'podman'

- name: Wait for SSH services
  wait_for:
    port: "{{ item.ssh_port }}"
    host: 127.0.0.1
    timeout: 30
  loop: "{{ containers_to_run }}"

- name: Display SSH connection commands
  debug:
    msg: |
      Container {{ item.name }} attivo! ({{ container_runtime }})
      SSH: ssh -i {{ ssh_key_path }} -p {{ item.ssh_port }} genericuser@127.0.0.1
  loop: "{{ containers_to_run }}"