---
- name: $ Start the circus $
  hosts: all  
  become: yes
  vars:
    jenkins_secret: "0B82455D63A54029911503747DA33B12"  #this is random pass-code only to able jenkins-agent correctly work line. 69
  tasks:
    - name: Add official docker repo
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo  #to avoid recursive dowloads
    - name: Install Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    # - name: Create Jenkins home directory
    #   file:      
    #     path: /home/vagrant/jenkins_home2
    #     state: directory
    #     mode: '0766' 
    - name: Install python3-pip 
      dnf: #package manager of system 
        name: python3-pip
        state: present
    - name: Install required Python packages
      ansible.builtin.pip: #package manager of python
        name: requests
        state: present
      become: yes
    - name: Starting docker
      service:
        name: docker
        state: started 
        enabled: true #sudo su
    - name: Chmod docker.sock
      command: sudo chmod 666 /var/run/docker.sock
    - name: Create docker-network
      docker_network:
        name: circus_network
        driver: bridge #default
        ipam_config:
        - subnet: 192.168.50.0/24
    # - name: Ensure jenkins user exists
    #   ansible.builtin.user:
    #     name: jenkins
    #     shell: /bin/bash
    #     state: present
    # - name: Set owner of Jenkins home directory to jenkins
    #   file:
    #     path: /jenkins_home2
    #     owner: jenkins
    #     group: jenkins
    #     state: directory
    #     mode: '0766'
    - name: Launch Jenkins-master
      community.docker.docker_container: #module who manage docker 
        name: jenkins-master
        image: jenkins/jenkins:2.480-jdk21
        state: started
        volumes:
          - /jenkins_home2:/var/jenkins_home
        # volumes:
        #   - "jenkins-data:/var/jenkins_home"
        ports:
          - "8080:8080" #recommended from repo
          - "50000:50000" #recommended from repo
        networks:
          - name: circus_network  
            ipv4_address: 192.168.50.7
        env:
          JAVA_OPTS: "-Djenkins.model.Jenkins.slaveAgentPort=50000" 
          JENKINS_SLAVE_AGENT_PORT: "50000"
    - name: Launch jenkins-agent
      community.docker.docker_container:
        name: jenkins-agent
        image: jenkins/inbound-agent:latest
        state: started 
        env:
          JENKINS_URL: "http://192.168.50.7:8080"
          JENKINS_AGENT_NAME: "jenkins-agent"
          JENKINS_AGENT_WORKDIR: "/home/jenkins"
          JENKINS_SECRET: "{{ jenkins_secret }}" 
        volumes:
          - jenkins_slave_home:/home/jenkins/agent
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker
        networks:
          - name: circus_network  
            ipv4_address: 192.168.50.8