Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"  
  config.vm.box_version = "4.3.12"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.network "forwarded_port", guest: 8080, host: 8088
  config.vm.synced_folder "./jenkins_home1", "/jenkins_home2"
  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "playbook.yaml"
end
end