Vagrant.configure("2") do |config|
 config.vm.define "debian" do |debian|
  debian.vm.box = "generic/debian11"
  debian.vm.box_version = "4.3.12"
  debian.vm.network "private_network", ip: "192.168.56.20"
  debian.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update --fix-missing
    sudo apt install apache2 -y
    sudo systemctl enable apache2@
    echo '<html><head><title>Example</title></head><body><h1>~anmedyns</h1><p>Hello DevOpsTribe!</p></body></html>' | sudo tee /var/www/html/index.html
  SHELL
 end
 config.vm.define "rocky9" do |rocky|
  rocky.vm.box = "eurolinux-vagrant/rocky-9"
  rocky.vm.box_version = "9.4.5"
  rocky.vm.network "private_network", ip: "192.168.56.10"
  rocky.vm.disk :disk, name: "bingo", size: "1GB"
  rocky.vm.provision "shell", inline: <<-SHELL
    echo 'echo "=== Welcome in VM ==="' >> /home/vagrant/.bashrc
    echo 'echo "=== Try this cmd --> curl http://192.168.56.20 ===" ' >> /home/vagrant/.bashrc
    sudo parted /dev/sdb --script mklabel gpt
    sudo parted /dev/sdb --script -- mkpart primary ext4 0 1000M
    sudo mkfs.ext4 /dev/sdb1
    export TARGET_DISK=$(sudo blkid /dev/sdb1 -s UUID -o value)
    sudo echo "UUID=$TARGET_DISK / ext4 defaults 0 2" | sudo tee -a /etc/fstab
    sudo mount -a
    sudo parted $TARGET_DISK print
  SHELL
 end
end

